githubschool/funny-lemur

amuodd-hometown.md
this pull request adds a file with things to do and places to eat at Toronto, Ontario, Canada.  This PR resolves #90
@JinkyungLim Hey Jin!  What do you like to eat?  What types of things do you like to do?
=> Amuodd toronto

githubteacher-hometown.md
This pull request adds a file with things to do and places to eat in Fuquay Varina, NC. This PR resolves #6.
@andrericardo what do you like to eat? What types of things do you like to do?
=> Adding a file for Fuquay Varina, NC

nmessier86-hometown.md
This pull request adds a file with things to do and places to eat in Manchester, NH. This PR resolves #9.
=> Adding a file for Manchester, NH

myersb-cary.md
Stuff about Cary, NC.  The PR will resolve #30
=> Myersb rtp

pratapvedula.md
adding a file for list of things to do in aldie , va . This will resolve  #43
=> add a file for Aldie, Va

perrej1-testfile
This pull request adds a file with things to do and places to eat.  This PR resolves #33
=> Perrej1 my branch Adding a test file

zenjen_houston.md
This pull request adds a file with things to do and places to eat in Houston, TX. This PR resolves #6 .
=> Adding categories to zenjen_houston file

jgboyd-hometown.md
Pull request for adding a file with places to eat and things to do in Dublin NH. This PR resolves #26.
@groberge what would you do in manchester?
=> Adding a file for Dublin NH

chandreshsharma-mumbai.md
This pull request adds a file with things to do and places to visit in Mumbai. This PR resolves #4.
=> Adding a File for Mumbai

edoardomarsili-hometown.md
=> Edoardomarsili florence

ireeve-austin.md
Pull request adds a file for things to do and places to eat in Austin Texas
#7
=> adding file for Austin, TX

can-branch-hometown.md
=> Can branch

wca2000-topsfield.md
This pull request adds a file with places to eat and things to do in Topsfield, MA.  This PR resolves #8.   
@kylemacey what do you like to eat?  what types of things do you like to do?
=> Adding a file for Topsfield, MA

codeShar_hometown.md
This pull request adds a file with things to do and places to eat in Framingham MA. This PR resolves #6
=> Adding a file for Framingham MA

brentd-smith-hometown.md
This pull request adds a file and resolves #5
=> Brentd smith lexington ky

mschibilla-Mpls.md
This pull request adds a file for Minneapolis stuff.
This PR resolves #35
=> Adding a file for Minneapolis, MN

calebbontrager-milfordDE.md
This pull request is to add a markdown file with things to do and places to eat in Milford, DE. This PR addresses  #24.
=> Adding a MarkDown Doc for Milford, DE

lily08-portland.md
=> adding sections for where to eat Portland

LarryLopez-NewBosotnNH.md
=> Adding a file Larry lopez new boston nh

cardani-hometown.md
Add a file for Shrewsbury, MA for larry cardani.  
This resolve #6
=> Cardani branch - add file for Shrewsbury, MAS

neuwib-branch-hometown.md
This pull request adds a file with things to do and places to eat in Westborough MA. This PR resolves #3.
=> Adding a file for Westborough, MA

AnnMajeske-hometown.md
This pull request adds a file with things to do and places to eat in Greenfield NH.  This PR resolves #6.
=> Ann majeske greenfield nh

ramukmg-hyd.md
This pull request adds a file with things to do and places to eat in Hyderabad, India. This PR resolves #20.
@beardofedu What things would you like to at this place?
=> Ramu hyd: Adding a file for Hyderabad

nikhil-mumbai.md
This file is for testing and used to show/test basic use of git
@chandreshsharma This is just a testing. Please review :) !!!
=> Githubtraining adding file and showing an example

ramukmg-hyd.md, ramukmlg-Hyderabad-India.md
Rename file ramukmg-hyd.md to ramukmlg-Hyderabad-India.md
=> RamuKMLG: Rename file ramukmg-hyd.md to ramukmlg-Hyderabad-India.md

cardani-shrewsbury.md
=> Test merging my Shrewsbury MA changes
